volumes:
  postgres-data:


services:
  reactapp:
    build: ./frontend
    tty: true
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    env_file:
      - .env
  goapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
